#!/bin/bash
PATH="$PWD/node_modules/.bin":$PATH
set -e

build() {
    set -x
    rm -rf dist
    nest build
    set +x
}

build_wp() {
    set -x
    rm -rf dist
    nest build --webpack
    set +x
}

build_swc() {
    set -x
    rm -rf dist
    export NODE_ENV=production
    swc src --source-maps=true -d dist
    set +x
}

build_vite() {
    set -x
    export NODE_ENV=production
    vite build --sourcemap
    set +x
}

"$@"
