#!/bin/bash
PATH="$PWD/node_modules/.bin":$PATH
set -e

build() {
    set -x
    rm -rf dist
    nest build
    set +x
}

build_wp() {
    set -x
    rm -rf dist
    nest build --webpack
    set +x
}

"$@"
